In [1]:
import tensorflow as tf

In [2]:
matrix1 = tf.Variable([
    [-0.013, 0.024, 0.06, 0.022],
    [0.001, -0.047, 0.039, 0.016],
    [0.018, 0.030, -0.021, -0.028]
])

matrix1

2023-03-22 13:02:59.657231: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-22 13:02:59.658580: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.013,  0.024,  0.06 ,  0.022],
       [ 0.001, -0.047,  0.039,  0.016],
       [ 0.018,  0.03 , -0.021, -0.028]], dtype=float32)>

In [9]:
msrp_matrix = tf.Variable([
    [19999.95],
    [24995.50],
    [36745.50],
    [29995.95]
])
msrp_matrix

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[19999.95],
       [24995.5 ],
       [36745.5 ],
       [29995.95]], dtype=float32)>

In [6]:
bias_tensor = tf.Variable([
    [2500],
    [2500],
    [2500]
], dtype=tf.float32)
bias_tensor

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[2500.],
       [2500.],
       [2500.]], dtype=float32)>

In [10]:
result = tf.subtract(tf.matmul(matrix1, msrp_matrix), bias_tensor)
result

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[  704.53345],
       [-1741.7787 ],
       [-3001.6782 ]], dtype=float32)>

In [11]:
tf.keras.activations.relu(result)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[704.53345],
       [  0.     ],
       [  0.     ]], dtype=float32)>