In [1]:
import tensorflow as tf

In [2]:
matrix1 = tf.Variable([
    [1.0, 0, 3.0, 1.0, 2.0],
    [0, 1.0, 1.0, 1.0, 1.0],
    [2.0, 1.0, 0, 2.0, 0]
])

2023-03-22 10:05:04.281506: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-22 10:05:04.283396: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [3]:
matrix1

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[1., 0., 3., 1., 2.],
       [0., 1., 1., 1., 1.],
       [2., 1., 0., 2., 0.]], dtype=float32)>

In [4]:
matrix1.shape.as_list()

[3, 5]

In [5]:
matrix2 = tf.Variable([
    [0.49, 103],
    [0.18, 38],
    [0.24, 69],
    [1.02, 75],
    [0.68, 78]
])
matrix2

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[  0.49, 103.  ],
       [  0.18,  38.  ],
       [  0.24,  69.  ],
       [  1.02,  75.  ],
       [  0.68,  78.  ]], dtype=float32)>

In [6]:
matrix2.shape.as_list()

[5, 2]

In [7]:
matmul1 = tf.matmul(matrix1, matrix2)
matmul1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[  3.5900002, 541.       ],
       [  2.1200001, 260.       ],
       [  3.2      , 394.       ]], dtype=float32)>

In [10]:
matrix3 = tf.Variable([
    [120, 100, 90],
    [30, 15, 20],
    [220, 240, 185],
    [145, 160, 155],
    [330, 295, 290]
], dtype=tf.float32)
matrix3

<tf.Variable 'Variable:0' shape=(5, 3) dtype=float32, numpy=
array([[120., 100.,  90.],
       [ 30.,  15.,  20.],
       [220., 240., 185.],
       [145., 160., 155.],
       [330., 295., 290.]], dtype=float32)>

In [11]:
matmul3 = matrix3 @ matmul1
matmul3

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[9.3080005e+02, 1.2638000e+05],
       [2.0350000e+02, 2.8010000e+04],
       [1.8906001e+03, 2.5431000e+05],
       [1.3557501e+03, 1.8111500e+05],
       [2.7381001e+03, 3.6949000e+05]], dtype=float32)>