In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.8.2'

In [3]:
scalar1 = tf.Variable(5)
scalar1

2023-03-14 17:04:18.803785: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-14 17:04:18.805672: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

In [4]:
vector1 = tf.Variable([1,2,3,4,5], dtype=tf.int16)
vector1

<tf.Variable 'Variable:0' shape=(5,) dtype=int16, numpy=array([1, 2, 3, 4, 5], dtype=int16)>

In [5]:
vector1.shape

TensorShape([5])

In [6]:
vector1.trainable

True

In [7]:
matrix1 = tf.Variable([[1,2,3],[4,5,6]], dtype=tf.int32)
matrix1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [8]:
matrix1.shape

TensorShape([2, 3])

In [9]:
tf.rank(matrix1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [10]:
scalar1.numpy()

5

In [11]:
matrix1.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [12]:
matrix1.shape.as_list()

[2, 3]

In [15]:
tf.rank(vector1).numpy()

1

In [ ]:
location_x = tf.Variable([[2706, 2799, 5102],
                         [2386, 4089, 5932]], tf.int32)
location_y = tf.Variable([[]])