In [1]:
import tensorflow as tf

In [2]:
tensor1 = tf.Variable([1,2,3])
tensor2 = tf.Variable([4,5,6])

2023-03-16 10:26:14.829435: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-16 10:26:14.830815: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [3]:
tensor_add_1 = tf.add(tensor1, tensor2)
tensor_add_1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [4]:
int1 = tf.Variable(4113, tf.int32)
int2 = tf.Variable(7511, tf.int32)
int3 = tf.Variable(6529, tf.int32)

In [5]:
int_sum = int1 + int2 + int3

In [6]:
int_sum.numpy()

18153

In [7]:
int_sum

<tf.Tensor: shape=(), dtype=int32, numpy=18153>

In [8]:
vec1 = tf.Variable([4113, 3870, 5102], dtype=tf.int32)
vec2 = tf.Variable([7511, 6725, 7038], dtype=tf.int32)
vec3 = tf.Variable([6529, 6962, 6591], dtype=tf.int32)

In [9]:
vec_sum = vec1 + vec2 + vec3

In [10]:
vec_sum

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([18153, 17557, 18731], dtype=int32)>

In [11]:
vec_sum.numpy()

array([18153, 17557, 18731], dtype=int32)

In [12]:
(vec1[0] + vec2[0] + vec3[0]).numpy()

18153

In [13]:
(vec1[1] + vec2[1] + vec3[1]).numpy()

17557

In [14]:
matrix1 = tf.Variable([[4113, 3870, 5102],
                      [3611, 951, 870]], tf.int32)
matrix2 = tf.Variable([[7511, 6725, 7038],
                      [5901, 1208, 645]], tf.int32)
matrix3 = tf.Variable([[6529, 6962, 6591],
                      [6235, 1098, 948]], tf.int32)

In [15]:
matrix1.shape == matrix2.shape == matrix3.shape

True

In [16]:
matrix_sum = matrix1 + matrix2 + matrix3

In [17]:
matrix_sum.numpy()

array([[18153, 17557, 18731],
       [15747,  3257,  2463]], dtype=int32)

In [18]:
location_x = tf.Variable([[2706, 2799, 5102],
                         [2386, 4089, 5932]], tf.int32)
location_y = tf.Variable([[5901, 1208, 645],
                         [6235, 1098, 948]], tf.int32)
location_z = tf.Variable([[3908, 2339, 5520],
                         [4544, 1978, 4729]], tf.int32)

In [19]:
sales_1 = tf.Variable(2706, tf.int32)
sales_2 = tf.Variable(2386, tf.int32)

In [20]:
product_a_x = sales_1 + sales_2
product_a_x.numpy()

5092

In [21]:
vec_1 = tf.Variable([2706, 2799, 5102], tf.int32)
scal_1 = tf.Variable(95, tf.int32)

In [22]:
(vec_1 + scal_1).numpy()

array([2801, 2894, 5197], dtype=int32)

In [23]:
(location_x + location_y + location_z).numpy()

array([[12515,  6346, 11267],
       [13165,  7165, 11609]], dtype=int32)

In [24]:
tensor1 = tf.Variable([1,2,3,4,5,6])
tensor_reshape = tf.reshape(tensor1, shape=[3,2])

In [25]:
tensor_reshape.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [26]:
tensor_transpose = tf.transpose(tensor1)
tensor_transpose.numpy()

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [27]:
tensor1.numpy()

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [28]:
tensor_transpose

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [29]:
(tf.transpose(tensor_reshape)).numpy()

array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)

In [30]:
matrix1 = tf.Variable([[1,2,3,4],[5,6,7,8]])

In [32]:
matrix1.shape.as_list()

[2, 4]

In [33]:
reshape1 = tf.reshape(matrix1, shape=[4,2])
reshape1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [34]:
reshape2 = tf.reshape(matrix1, shape=[1,8])
reshape2.numpy()

array([[1, 2, 3, 4, 5, 6, 7, 8]], dtype=int32)

In [35]:
reshape3 = tf.reshape(matrix1, shape=[8, 1])
reshape3.numpy()

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)

In [36]:
reshape4 = tf.reshape(matrix1, shape=[2,2,2])
reshape4.numpy()

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

In [37]:
transpose1 = tf.transpose(matrix1)
transpose1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int32)>

In [38]:
reshape1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [39]:
tensor1 = tf.Variable([[1,2,3]])
tensor2 = tf.Variable([[1], [2], [3]])

In [40]:
tensor1

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [41]:
tensor2

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [42]:
tensor_matmul = tf.matmul(tensor1, tensor2)
tensor_matmul

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [43]:
tensor_matmul.numpy()

array([[14]], dtype=int32)

In [44]:
tensor1.numpy()

array([[1, 2, 3]], dtype=int32)

In [45]:
tensor2.numpy()

array([[1],
       [2],
       [3]], dtype=int32)

In [46]:
tensor1 = tf.Variable([[1,2,3]])
scalar_mult = 5 * tensor1

In [47]:
scalar_mult.numpy()

array([[ 5, 10, 15]], dtype=int32)